# _config.yml

# Site settings
title: 水镜的博客
description: A blog dedicated to tutorials and insights on technology, coding, and more.
url: "htpps://www.verumkey.com" # 你的网站地址，如果部署后会替换为实际网址
baseurl: "" # 如果你将网站部署在子目录下，设置为"/your-repo"

# Author settings
author:
  name: secrecy
  email: verumkeys@gmail.com

# Build settings
markdown: kramdown # 使用的 Markdown 渲染器
theme: minima # 主题设置，可以根据需求更改

# Social settings
social:
  github: https://github.com/Verumkey
  email: verumkeys@gmail.com

# Plugins
# plugins:
# - jekyll-feed # RSS 订阅支持

# Permalinks
permalink: pretty # 设置固定链接格式为漂亮的链接

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config.yml

# Build settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# Additional settings
# You can add more configurations as needed
